repos:
  - repo: https://github.com/pycqa/flake8
    rev: '3.8.3'
    hooks:
      - id: flake8
        name: Linting
        stages:
          - commit
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
      - id: mypy
        name: Type Checking
        entry: poetry run mypy favicons
        pass_filenames: false
